name: Deploy Blog Post

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name : Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Set up Azure CLI
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo "Azure CLI set up"
          az account show
          az storage -h
      

    - name: Upload Changed Files to Azure Blob Storage
      run: |
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            content=$(cat "$file" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
            json="{\"PartitionKey\":\"Category\",\"RowKey\":\"$(basename "$file")\",\"Content\":\"$content\"}"
            az storage entity insert --account-name 'stredstashita' --table-name 'posts' --entity "$json"
          fi
        done < changed_files.txt